---
- name: stop service
  become: true
  command: /etc/init.d/keycloak stop
  poll: 5
  async: 5
  ignore_errors: true

- name: wait for keycloak to stop
  wait_for:
    port: 8088
    state: stopped
    delay: 5
    sleep: 5
    timeout: 60
  ignore_errors: true
- name: start service
  become: true
  command: /etc/init.d/keycloak start
  ignore_errors: true

- name: wait for keycloak to start
  uri:
    url: "http://{{ inventory_hostname }}:8088/auth/"
    method: GET
  register: _result
  until: _result.status == 200
  delay: 5
  retries: 60
